App.i18n = {
    ua: {
        logo_tagline: "Твій стиль • Гаджети • Дропи",
        catalog_btn: "Каталог",
        search_placeholder: "Знайти товар...",
        cat_all: "🔥 Все",
        cat_china: "🇨🇳 Китай",
        cat_clothes: "👕 Одяг",
        cat_electronics: "📱 Електро",
        cat_accessories: "💎 Аксесуари",
        cat_favorites: "❤️ Обране",
        section_products: "✨ Товари",
        section_cart: "🛒 Кошик",
        section_favorites: "❤️ Обране",
        section_profile: "👤 Профіль",
        section_settings: "⚙️ Налаштування",
        section_orders: "📦 Історія замовлень",
        cart_empty: "Кошик порожній",
        cart_empty_desc: "Додайте товари з каталогу",
        cart_items_count: "Товарів:",
        cart_total: "Разом:",
        checkout_btn: "🚀 Оформити замовлення",
        nav_home: "Головна",
        nav_favorites: "Обране",
        nav_cart: "Кошик",
        nav_profile: "Профіль",
        modal_to_cart: "В кошик",
        modal_in_cart: "✓ В кошику",
        toast_added: "✅ Додано в кошик",
        toast_count_updated: "✅ Кількість оновлена",
        toast_wishlist_added: "❤️ Додано в обране",
        wishlist_empty: "Обране порожнє",
        wishlist_empty_desc: "Додайте товари до обраного",
        profile_guest: "Гість",
        profile_no_username: "Немає юзернейма",
        profile_lang: "Мова",
        profile_theme: "Тема",
        profile_theme_dark: "Темна",
        profile_orders_empty: "Історія замовлень порожня",
        badge_new: "🆕 Нове",
        badge_second: "♻️ Секонд",
        cat_modal_title: "📦 Каталог",
        search_modal_title: "🔍 Пошук",
        hero_new_title: "Нові<br>Дропи",
        hero_new_sub: "Стиль майбутнього.",
        hero_check_btn: "Дивитись",
        hero_sale_title: "Гаряча<br>Ціна",
        hero_sale_sub: "-50% ЗНИЖКИ",
        hero_go_btn: "Вперед!",
        p1_name: "TWS Навушники i12",
        p1_desc: "Бездротові навушники Apple-style, Bluetooth 5.0, сенсорне керування",
        p2_name: "PowerBank 20000mAh",
        p2_desc: "Портативна зарядка з швидкою зарядкою QC3.0, 2 USB порти",
        p3_name: "LED Кільце для селфі",
        p3_desc: "Кільцева лампа 26см з тримачем для телефону, 3 режими світла",
        p4_name: "USB-C Хаб 7в1",
        p4_desc: "Адаптер для MacBook: HDMI, USB 3.0, SD карта, зарядка",
        p5_name: "Vintage Джинсовка",
        p5_desc: "Оверсайз куртка Levi's 90х, чудовий стан, розмір M-L",
        p6_name: "Худі Champion",
        p6_desc: "Оригінальне худі, тепле з начісом, розмір L",
        p7_name: "Кросівки Nike AF1",
        p7_desc: "Air Force 1 Low, білі, стан 8/10, розмір 42",
        p8_name: "Карго штани",
        p8_desc: "Широкі карго в стилі Y2K, багато кишень, розмір M",
        p9_name: "Смарт-годинник M8",
        p9_desc: "Фітнес браслет з великим екраном, пульс, кроки, сповіщення",
        p10_name: "Міні проектор",
        p10_desc: "LED проектор для дому, підтримка 1080p, HDMI вхід",
        p11_name: "Сумка через плече",
        p11_desc: "Компактная crossbody сумка, нейлон, багато відділень",
        p12_name: "Сонцезахисні окуляри",
        p12_desc: "Ретро стиль, UV400 захист, металева оправа",
        p13_name: "Кепка NY Yankees",
        p13_desc: "Бейсболка чорна, регульований розмір, вишивка",
        p14_name: "Ланцюжок срібло",
        p14_desc: "Ланцюжок-мотузка 50см, покриття під срібло",
        app_title: "China & Second Shop",
        logo_name: "DROP STATION",
        search_start_typing: "Почніть вводити назву товару",
        search_nothing_found: "Нічого не знайдено",
        cat_all_items: "Всі товари",
        cat_china_name: "Китай",
        cat_clothes_name: "Одяг",
        cat_electronics_name: "Електроніка",
        cat_accessories_name: "Аксесуари",
        cat_favorites_name: "Обране",
        cat_electronics_full: "Електроніка",
        cat_favorites_full: "Обране",
        search_title: "Пошук",
        search_input_placeholder: "Знайти товар...",
        checkout_button: "🚀 Оформити замовлення",
        badge_hot_text: "HOT SALE",
        badge_new_text: "НОВИНКА",
        badge_sale_text: "SALE",
        badge_limited_text: "LIMITED",
        badge_discount_text: "-15%",
        badge_exclusive_text: "EXCLUSIVE",
        badge_free_delivery: "Free Delivery",
        badge_trend: "🔥 TREND",
        badge_hit: "⭐ HIT",
        btn_to_favorites_title: "В обране",
        btn_quick_view_title: "Швидкий перегляд",
        btn_add_to_cart: "🛒 В кошик",
        btn_remove_from_favorites_title: "Видалити з обраного"
    },
    ru: {
        logo_tagline: "Твой стиль • Гаджеты • Дропы",
        catalog_btn: "Каталог",
        search_placeholder: "Найти товар...",
        cat_all: "🔥 Все",
        cat_china: "🇨🇳 Китай",
        cat_clothes: "👕 Одежда",
        cat_electronics: "📱 Электро",
        cat_accessories: "💎 Аксессуары",
        cat_favorites: "❤️ Избранное",
        section_products: "✨ Товары",
        section_cart: "🛒 Корзина",
        section_favorites: "❤️ Избранное",
        section_profile: "👤 Профиль",
        section_settings: "⚙️ Настройки",
        section_orders: "📦 История заказов",
        cart_empty: "Корзина пуста",
        cart_empty_desc: "Добавьте товары из каталога",
        cart_items_count: "Товаров:",
        cart_total: "Итого:",
        checkout_btn: "🚀 Оформить заказ",
        nav_home: "Главная",
        nav_favorites: "Избранное",
        nav_cart: "Корзина",
        nav_profile: "Профиль",
        modal_to_cart: "В корзину",
        modal_in_cart: "✓ В корзине",
        toast_added: "✅ Добавлено в корзину",
        toast_count_updated: "✅ Количество обновлено",
        toast_wishlist_added: "❤️ Добавлено в избранное",
        wishlist_empty: "Избранное пусто",
        wishlist_empty_desc: "Добавьте товары в избранное",
        profile_guest: "Гость",
        profile_no_username: "Нет юзернейма",
        profile_lang: "Язык",
        profile_theme: "Тема",
        profile_theme_dark: "Тёмная",
        profile_orders_empty: "История заказов пуста",
        badge_new: "🆕 Новое",
        badge_second: "♻️ Секонд",
        cat_modal_title: "📦 Каталог",
        search_modal_title: "🔍 Поиск",
        hero_new_title: "Новые<br>Дропы",
        hero_new_sub: "Стиль будущего.",
        hero_check_btn: "Смотреть",
        hero_sale_title: "Горячая<br>Цена",
        hero_sale_sub: "-50% СКИДКИ",
        hero_go_btn: "Вперед!",
        p1_name: "TWS Наушники i12",
        p1_desc: "Беспроводные наушники Apple-style, Bluetooth 5.0, сенсорное управление",
        p2_name: "PowerBank 20000mAh",
        p2_desc: "Портативная зарядка с быстрой зарядкой QC3.0, 2 USB порта",
        p3_name: "LED Кольцо для селфи",
        p3_desc: "Кольцевое лампа 26см с держателем для телефона, 3 режима света",
        p4_name: "USB-C Хаб 7в1",
        p4_desc: "Адаптер для MacBook: HDMI, USB 3.0, SD карта, зарядка",
        p5_name: "Vintage Джинсовка",
        p5_desc: "Оверсайз куртка Levi's 90х, отличное состояние, размер M-L",
        p6_name: "Худи Champion",
        p6_desc: "Оригинальное худи, теплое с начесом, размер L",
        p7_name: "Кроссовки Nike AF1",
        p7_desc: "Air Force 1 Low, белые, состояние 8/10, размер 42",
        p8_name: "Карго штаны",
        p8_desc: "Широкие карго в стиле Y2K, many pockets, размер M",
        p9_name: "Смарт-часы M8",
        p9_desc: "Фитнес браслет с большим экраром, пульс, шаги, уведомления",
        p10_name: "Мини проектор",
        p10_desc: "LED проектор для дома, поддержка 1080p, HDMI вход",
        p11_name: "Сумка через плечо",
        p11_desc: "Компактная crossbody сумка, нейлон, много отделений",
        p12_name: "Солнцезащитные очки",
        p12_desc: "Ретро стиль, UV400 защита, металлическая оправа",
        p13_name: "Кепка NY Yankees",
        p13_desc: "Бейсболка черная, регулируемый размер, вышивка",
        p14_name: "Цепочка серебро",
        p14_desc: "Цепочка-веревка 50см, покрытие под серебро",
        app_title: "China & Second Shop",
        logo_name: "DROP STATION",
        search_start_typing: "Начните вводить название товара",
        search_nothing_found: "Ничего не найдено",
        cat_all_items: "Все товары",
        cat_china_name: "Китай",
        cat_clothes_name: "Одежда",
        cat_electronics_name: "Электроника",
        cat_accessories_name: "Аксессуары",
        cat_favorites_name: "Избранное",
        cat_electronics_full: "Электроника",
        cat_favorites_full: "Избранное",
        search_title: "Поиск",
        search_input_placeholder: "Найти товар...",
        checkout_button: "🚀 Оформить заказ",
        badge_hot_text: "HOT SALE",
        badge_new_text: "НОВИНКА",
        badge_sale_text: "SALE",
        badge_limited_text: "LIMITED",
        badge_discount_text: "-15%",
        badge_exclusive_text: "EXCLUSIVE",
        badge_free_delivery: "Free Delivery",
        badge_trend: "🔥 TREND",
        badge_hit: "⭐ HIT",
        btn_to_favorites_title: "В избранное",
        btn_quick_view_title: "Быстрый просмотр",
        btn_add_to_cart: "🛒 В корзину",
        btn_remove_from_favorites_title: "Удалить из избранного"
    },
    en: {
        logo_tagline: "Your Style • Gadgets • Drops",
        catalog_btn: "Catalog",
        search_placeholder: "Search products...",
        cat_all: "🔥 All",
        cat_china: "🇨🇳 China",
        cat_clothes: "👕 Clothes",
        cat_electronics: "📱 Electro",
        cat_accessories: "💎 Accessories",
        cat_favorites: "❤️ Favorites",
        section_products: "✨ Products",
        section_cart: "🛒 Cart",
        section_favorites: "❤️ Favorites",
        section_profile: "👤 Profile",
        section_settings: "⚙️ Settings",
        section_orders: "📦 Order History",
        cart_empty: "Cart is empty",
        cart_empty_desc: "Add products from catalog",
        cart_items_count: "Items:",
        cart_total: "Total:",
        checkout_btn: "🚀 Checkout",
        nav_home: "Home",
        nav_favorites: "Favorites",
        nav_cart: "Cart",
        nav_profile: "Profile",
        modal_to_cart: "To Cart",
        modal_in_cart: "✓ In Cart",
        toast_added: "✅ Added to cart",
        toast_count_updated: "✅ Quantity updated",
        toast_wishlist_added: "❤️ Added to favorites",
        wishlist_empty: "Favorites is empty",
        wishlist_empty_desc: "Add products to favorites",
        profile_guest: "Guest",
        profile_no_username: "No username",
        profile_lang: "Language",
        profile_theme: "Theme",
        profile_theme_dark: "Dark",
        profile_orders_empty: "Order history is empty",
        badge_new: "🆕 New",
        badge_second: "♻️ Second Hand",
        cat_modal_title: "📦 Catalog",
        search_modal_title: "🔍 Search",
        hero_new_title: "New<br>Drops",
        hero_new_sub: "Future styles.",
        hero_check_btn: "Check",
        hero_sale_title: "Hot<br>Sale",
        hero_sale_sub: "-50% OFF",
        hero_go_btn: "Go!",
        p1_name: "TWS Earphones i12",
        p1_desc: "Apple-style wireless earbuds, Bluetooth 5.0, touch control",
        p2_name: "PowerBank 20000mAh",
        p2_desc: "Portable charger with QC3.0 fast charging, 2 USB ports",
        p3_name: "LED Selfie Ring",
        p3_desc: "26cm ring light with phone holder, 3 light modes",
        p4_name: "USB-C Hub 7in1",
        p4_desc: "MacBook adapter: HDMI, USB 3.0, SD card, charging",
        p5_name: "Vintage Denim Jacket",
        p5_desc: "Oversized Levi's 90s jacket, great condition, size M-L",
        p6_name: "Champion Hoodie",
        p6_desc: "Original hoodie, warm with fleece, size L",
        p7_name: "Nike AF1 Sneakers",
        p7_desc: "Air Force 1 Low, white, 8/10 condition, size 42",
        p8_name: "Cargo Pants",
        p8_desc: "Wide Y2K style cargo pants, many pockets, size M",
        p9_name: "Smart Watch M8",
        p9_desc: "Fitness tracker with large screen, heart rate, steps, notifications",
        p10_name: "Mini Projector",
        p10_desc: "LED home projector, 1080p support, HDMI input",
        p11_name: "Crossbody Bag",
        p11_desc: "Compact crossbody bag, nylon, multiple compartments",
        p12_name: "Sunglasses",
        p12_desc: "Retro style, UV400 protection, metal frame",
        p13_name: "NY Yankees Cap",
        p13_desc: "Black baseball cap, adjustable size, embroidery",
        p14_name: "Silver Chain",
        p14_desc: "Rope chain 50cm, silver plating",
        app_title: "China & Second Shop",
        logo_name: "DROP STATION",
        search_start_typing: "Start typing product name...",
        search_nothing_found: "Nothing found",
        cat_all_items: "All Products",
        cat_china_name: "China",
        cat_clothes_name: "Clothes",
        cat_electronics_name: "Electronics",
        cat_accessories_name: "Accessories",
        cat_favorites_name: "Favorites",
        cat_electronics_full: "Electronics",
        cat_favorites_full: "Favorites",
        search_title: "Search",
        search_input_placeholder: "Find product...",
        checkout_button: "🚀 Checkout",
        badge_hot_text: "HOT SALE",
        badge_new_text: "NEW",
        badge_sale_text: "SALE",
        badge_limited_text: "LIMITED",
        badge_discount_text: "-15%",
        badge_exclusive_text: "EXCLUSIVE",
        badge_free_delivery: "Free Delivery",
        badge_trend: "🔥 TREND",
        badge_hit: "⭐ HIT",
        btn_to_favorites_title: "Add to favorites",
        btn_quick_view_title: "Quick view",
        btn_add_to_cart: "🛒 Add to cart",
        btn_remove_from_favorites_title: "Remove from favorites"
    }
};
